Do not transform (parse) commands that fail inside of a pipeline, like `#zrange` with invalid parameters and `with_scores` set to `true`. This last argument requires parsing of the result, but when the Redis server returns a `CommandError`, this string is attempted to be parsed, which fails with the following stacktrace:
```
/Users/javierhonduco/.gem/ruby/2.4.0/gems/redis-4.0.1/lib/redis.rb:2809:in
`block in <class:Redis>': undefined method `each_slice' for
  from
  /Users/javierhonduco/.gem/ruby/2.4.0/gems/redis-4.0.1/lib/redis/pipeline.rb:114:in
  `_set'
  from
  /Users/javierhonduco/.gem/ruby/2.4.0/gems/redis-4.0.1/lib/redis/pipeline.rb:61:in
  `block in finish'
  from
  /Users/javierhonduco/.gem/ruby/2.4.0/gems/redis-4.0.1/lib/redis/pipeline.rb:60:in
  `each'
  from
  /Users/javierhonduco/.gem/ruby/2.4.0/gems/redis-4.0.1/lib/redis/pipeline.rb:60:in
  `each_with_index'
  from
  /Users/javierhonduco/.gem/ruby/2.4.0/gems/redis-4.0.1/lib/redis/pipeline.rb:60:in
  `each'
  from
  /Users/javierhonduco/.gem/ruby/2.4.0/gems/redis-4.0.1/lib/redis/pipeline.rb:60:in
  `map'
  from
  /Users/javierhonduco/.gem/ruby/2.4.0/gems/redis-4.0.1/lib/redis/pipeline.rb:60:in
  `finish'
  from
  /Users/javierhonduco/.gem/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:155:in
  `block in call_pipeline'
  from
  /Users/javierhonduco/.gem/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:291:in
  `with_reconnect'
  from
  /Users/javierhonduco/.gem/ruby/2.4.0/gems/redis-4.0.1/lib/redis/client.rb:153:in
  `call_pipeline'
  from
  /Users/javierhonduco/.gem/ruby/2.4.0/gems/redis-4.0.1/lib/redis.rb:2307:in
  `block in pipelined'
  from
  /Users/javierhonduco/.gem/ruby/2.4.0/gems/redis-4.0.1/lib/redis.rb:45:in
  `block in synchronize'
  from
  /Users/javierhonduco/.rubies/ruby-2.4.0/lib/ruby/2.4.0/monitor.rb:214:in
  `mon_synchronize'
  from
  /Users/javierhonduco/.gem/ruby/2.4.0/gems/redis-4.0.1/lib/redis.rb:45:in
  `synchronize'
  from
  /Users/javierhonduco/.gem/ruby/2.4.0/gems/redis-4.0.1/lib/redis.rb:2303:in
  `pipelined'
  [...]
```